-- drop table ACCOUNT_HISTORY purge;
 
Create table ACCOUNT_HISTORY(
ACCOUNT_NO VARCHAR2(150) not null,
CUST_ID NUMBER(22) not null,
SEQNO NUMBER(22) not null,
CUSTOMER_ID_HIGH NUMBER(22) ,
HISTORY_VALID_FROM DATE not null,
HISTORY_VALID_TO DATE ,
--PRIMARY KEY (CUST_ID)
FOREIGN KEY (CUST_ID) REFERENCES ACCOUNT(CUST_ID)
)SEGMENT CREATION IMMEDIATE PCTFREE 10 PCTUSED 40 
INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 
MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT 
FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) TABLESPACE "PINTABLE" ;
 CREATE INDEX idx_ACCOUNT_HISTORY_ACCOUNT_NO ON ACCOUNT_HISTORY(ACCOUNT_NO);