-- drop table ACCT_ADDRESS purge;
 
Create table ACCT_ADDRESS(
ACCOUNT_NO VARCHAR2(150) not null,
CUST_ID NUMBER(22) not null,
SeqNo NUMBER(22) not null,
CONTACT_TYPE VARCHAR2(1) ,
SALUTATION NUMBER(22) ,
FIRST_NAME VARCHAR2(40) ,
MIDDLE_NAME VARCHAR2(10) ,
LAST_NAME VARCHAR2(40) ,
STREET_NO VARCHAR2(15) ,
CITY             VARCHAR2(40) ,
COUNTRY          NUMBER(22) ,
STATE VARCHAR2(25) ,
ZIP VARCHAR2(15) ,
EMAIL VARCHAR2(200) ,
CONTACT_NO VARCHAR2(25) ,
ALTERNATE_CONT_NO VARCHAR2(25) ,
GENDER VARCHAR2(1) ,
NATIONALITY NUMBER(22) ,
ADDRESS1 VARCHAR2(80) ,
ADDRESS2 VARCHAR2(80) ,
ADDRESS3 VARCHAR2(80) ,
ADDRESS4 VARCHAR2(80) ,
ADDRESS5 VARCHAR2(80) ,
ADDRESS6 VARCHAR2(80) ,
--PRIMARY KEY (CUST_ID)
FOREIGN KEY (CUST_ID) REFERENCES ACCOUNT(CUST_ID)
)SEGMENT CREATION IMMEDIATE PCTFREE 10 PCTUSED 40 
INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 
MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT 
FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) TABLESPACE "PINTABLE" ;
 CREATE INDEX idx_ACCT_ADDRESS_ACCOUNT_NO ON ACCT_ADDRESS(ACCOUNT_NO);