-- drop table CHARGE_EVENTS purge;
 
Create table CHARGE_EVENTS(
ACCOUNT_NO VARCHAR2(150) not null,
CUST_ID NUMBER(22) not null,
MSISDN NUMBER(22) not null,
EVENT_ID NUMBER(22) not null,
REMARK VARCHAR2(2000) ,
CHARGE_TYPE VARCHAR2(1) not null,
CYCLE_START DATE ,
CYCLE_END DATE ,
CHARGE_AMOUNT FLOAT(22) ,
TAX_CODE VARCHAR2(10) ,
GL_ID VARCHAR2(30) ,
PROGRAM_NAME NUMBER(22) ,
PERIOD NUMBER(22) ,
--PRIMARY KEY (CUST_ID)
FOREIGN KEY (CUST_ID) REFERENCES ACCOUNT(CUST_ID)
)SEGMENT CREATION IMMEDIATE PCTFREE 10 PCTUSED 40 
INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 
MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT 
FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) TABLESPACE "PINTABLE" ;
 CREATE INDEX idx_CHARGE_EVENTS_ACCOUNT_NO ON CHARGE_EVENTS(ACCOUNT_NO);