-- drop table PURCHASED_DISCOUNT purge;
 
Create table PURCHASED_DISCOUNT(
ACCOUNT_NO VARCHAR2(150) not null,
CUST_ID NUMBER(22) not null,
MSISDN NUMBER(22) not null,
PRODUCT_ID NUMBER(22) not null,
DESCRIPTION VARCHAR2(30) not null,
STATUS VARCHAR2(1) not null,
CREATED_DATE DATE not null,
DELETE_DATE DATE ,
ASSIGN_DATE DATE not null,
ASSIGN_SEQ NUMBER(22) not null,
SEQ NUMBER(22) not null,
--PRIMARY KEY (CUST_ID)
FOREIGN KEY (CUST_ID) REFERENCES ACCOUNT(CUST_ID)
)SEGMENT CREATION IMMEDIATE PCTFREE 10 PCTUSED 40 
INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 
MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT 
FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) TABLESPACE "PINTABLE" ;
 CREATE INDEX idx_PURCHASED_DISCOUNT_ACCOUNT_NO ON PURCHASED_DISCOUNT(ACCOUNT_NO);