-- drop table RATEPLAN_HIST purge;
 
Create table RATEPLAN_HIST(
ACCOUNT_NO VARCHAR2(150) not null,
CUST_ID NUMBER(22) not null,
MSISDN NUMBER(22) ,
CO_ID NUMBER(22) not null,
SEQNO NUMBER(22) not null,
TMCODE NUMBER(22) not null,
TMCODE_DATE DATE not null,
USERLASTMOD VARCHAR2(16) ,
REC_VERSION NUMBER(22) not null,
REQUEST_ID NUMBER(22) ,
TRANSACTIONNO NUMBER(22) not null,
AGE_OUT_DATE DATE ,
--PRIMARY KEY (CUST_ID)
FOREIGN KEY (CUST_ID) REFERENCES ACCOUNT(CUST_ID)
)SEGMENT CREATION IMMEDIATE PCTFREE 10 PCTUSED 40 
INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 
MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT 
FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) TABLESPACE "PINTABLE" ;
 CREATE INDEX idx_RATEPLAN_HIST_ACCOUNT_NO ON RATEPLAN_HIST(ACCOUNT_NO);